// <auto-generated />
using System;
using Airbnb.Infrastructure.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Airbnb.Infrastructure.Migrations
{
    [DbContext(typeof(AirbnbDbContext))]
    partial class AirbnbDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Airbnb.Domain.BoundedContexts.AddressManagement.Aggregates.AddressLegal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("AddressLegal");
                });

            modelBuilder.Entity("Airbnb.Domain.BoundedContexts.CoordinatesManagement.Aggregates.Coordinate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Latitude")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Longitude")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Coordinates");
                });

            modelBuilder.Entity("Airbnb.Domain.BoundedContexts.ProductAdditionalInfoManagement.Aggregates.Additional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AdditionalInfos");
                });

            modelBuilder.Entity("Airbnb.Domain.BoundedContexts.ProductAdvantageManagement.Aggregates.Advantage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Advantages");
                });

            modelBuilder.Entity("Airbnb.Domain.BoundedContexts.ProductFacilityManagement.Facility.Aggregates.Facility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IconName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Facilities");
                });

            modelBuilder.Entity("Airbnb.Domain.BoundedContexts.ProductFacilityManagement.ProductFacility.Aggregates.ProductFacility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FacilityId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProductFacilities");
                });

            modelBuilder.Entity("Airbnb.Domain.BoundedContexts.ProductFeatureManagement.Feature.Aggregates.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Forcibly")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Features");
                });

            modelBuilder.Entity("Airbnb.Domain.BoundedContexts.ProductFeatureManagement.ProductFeature.Aggregates.ProductFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FeatureId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProductFeatures");
                });

            modelBuilder.Entity("Airbnb.Domain.BoundedContexts.ProductRoomManagement.Aggregates.ProductRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProductRooms");
                });

            modelBuilder.Entity("Airbnb.Domain.BoundedContexts.ProductRulesManagement.Aggregates.Rule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MaxGuestsNumber")
                        .HasColumnType("int");

                    b.Property<int?>("MaxPetsNumber")
                        .HasColumnType("int");

                    b.Property<int?>("PetsAddedPrice")
                        .HasColumnType("int");

                    b.Property<bool>("PetsAllowed")
                        .HasColumnType("bit");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GuestRules");
                });

            modelBuilder.Entity("Airbnb.Domain.BoundedContexts.PropertyTypeManagement.Aggregates.ApartmentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PropertyType");

                    b.HasKey("Id");

                    b.ToTable("ApartmentType");
                });

            modelBuilder.Entity("Airbnb.Domain.BoundedContexts.RoomManagement.Aggregates.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Airbnb.Domain.DomainProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressLegalId")
                        .HasColumnType("int");

                    b.Property<int>("ApartmentTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddressLegalId");

                    b.HasIndex("ApartmentTypeId");

                    b.ToTable("DomainProduct");
                });

            modelBuilder.Entity("Airbnb.Domain.BoundedContexts.AddressManagement.Aggregates.AddressLegal", b =>
                {
                    b.OwnsOne("Airbnb.Domain.BoundedContexts.ProductManagement.ValueObjects.Address.AddressEnteties.Block", "Block", b1 =>
                        {
                            b1.Property<int>("AddressLegalId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Block");

                            b1.HasKey("AddressLegalId");

                            b1.ToTable("AddressLegal");

                            b1.WithOwner()
                                .HasForeignKey("AddressLegalId");
                        });

                    b.OwnsOne("Airbnb.Domain.BoundedContexts.ProductManagement.ValueObjects.Address.AddressEnteties.City", "City", b1 =>
                        {
                            b1.Property<int>("AddressLegalId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("City");

                            b1.HasKey("AddressLegalId");

                            b1.ToTable("AddressLegal");

                            b1.WithOwner()
                                .HasForeignKey("AddressLegalId");
                        });

                    b.OwnsOne("Airbnb.Domain.BoundedContexts.ProductManagement.ValueObjects.Address.AddressEnteties.Country", "Country", b1 =>
                        {
                            b1.Property<int>("AddressLegalId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Country");

                            b1.HasKey("AddressLegalId");

                            b1.ToTable("AddressLegal");

                            b1.WithOwner()
                                .HasForeignKey("AddressLegalId");
                        });

                    b.OwnsOne("Airbnb.Domain.BoundedContexts.ProductManagement.ValueObjects.Address.AddressEnteties.District", "District", b1 =>
                        {
                            b1.Property<int>("AddressLegalId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("District");

                            b1.HasKey("AddressLegalId");

                            b1.ToTable("AddressLegal");

                            b1.WithOwner()
                                .HasForeignKey("AddressLegalId");
                        });

                    b.OwnsOne("Airbnb.Domain.BoundedContexts.ProductManagement.ValueObjects.Address.AddressEnteties.Flat", "Flat", b1 =>
                        {
                            b1.Property<int>("AddressLegalId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Flat");

                            b1.HasKey("AddressLegalId");

                            b1.ToTable("AddressLegal");

                            b1.WithOwner()
                                .HasForeignKey("AddressLegalId");
                        });

                    b.OwnsOne("Airbnb.Domain.BoundedContexts.ProductManagement.ValueObjects.Address.AddressEnteties.House", "House", b1 =>
                        {
                            b1.Property<int>("AddressLegalId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("House");

                            b1.HasKey("AddressLegalId");

                            b1.ToTable("AddressLegal");

                            b1.WithOwner()
                                .HasForeignKey("AddressLegalId");
                        });

                    b.OwnsOne("Airbnb.Domain.BoundedContexts.ProductManagement.ValueObjects.Address.AddressEnteties.Region", "Region", b1 =>
                        {
                            b1.Property<int>("AddressLegalId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Region");

                            b1.HasKey("AddressLegalId");

                            b1.ToTable("AddressLegal");

                            b1.WithOwner()
                                .HasForeignKey("AddressLegalId");
                        });

                    b.Navigation("Block");

                    b.Navigation("City");

                    b.Navigation("Country");

                    b.Navigation("District");

                    b.Navigation("Flat");

                    b.Navigation("House");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Airbnb.Domain.BoundedContexts.ProductAdditionalInfoManagement.Aggregates.Additional", b =>
                {
                    b.OwnsOne("Airbnb.Domain.BoundedContexts.ProductAdditionalManagement.ValueObjects.CancelPolicy", "CancelPolicy", b1 =>
                        {
                            b1.Property<int>("AdditionalId")
                                .HasColumnType("int");

                            b1.Property<int>("FreeCancelationDays")
                                .HasColumnType("int");

                            b1.Property<int>("PartCancelationDays")
                                .HasColumnType("int");

                            b1.Property<int>("PartCancelationPercent")
                                .HasColumnType("int");

                            b1.HasKey("AdditionalId");

                            b1.ToTable("AdditionalInfos");

                            b1.WithOwner()
                                .HasForeignKey("AdditionalId");
                        });

                    b.OwnsMany("Airbnb.Domain.BoundedContexts.ProductAdditionalManagement.ValueObjects.HomeRule", "HomeRules", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("AdditionalId")
                                .HasColumnType("int");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("Id");

                            b1.HasIndex("AdditionalId");

                            b1.ToTable("HomeRule");

                            b1.WithOwner()
                                .HasForeignKey("AdditionalId");
                        });

                    b.OwnsMany("Airbnb.Domain.BoundedContexts.ProductAdditionalManagement.ValueObjects.SafetyRule", "SafetyRules", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("AdditionalId")
                                .HasColumnType("int");

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("Id");

                            b1.HasIndex("AdditionalId");

                            b1.ToTable("SafetyRule");

                            b1.WithOwner()
                                .HasForeignKey("AdditionalId");
                        });

                    b.Navigation("CancelPolicy");

                    b.Navigation("HomeRules");

                    b.Navigation("SafetyRules");
                });

            modelBuilder.Entity("Airbnb.Domain.DomainProduct", b =>
                {
                    b.HasOne("Airbnb.Domain.BoundedContexts.AddressManagement.Aggregates.AddressLegal", "AddressLegal")
                        .WithMany()
                        .HasForeignKey("AddressLegalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Airbnb.Domain.BoundedContexts.PropertyTypeManagement.Aggregates.ApartmentType", "ApartmentType")
                        .WithMany()
                        .HasForeignKey("ApartmentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddressLegal");

                    b.Navigation("ApartmentType");
                });
#pragma warning restore 612, 618
        }
    }
}
