version: "3.8"

services:

  airbnb-api:
    build:
      context: .
      dockerfile: Airbnb.ProductManagement/Airbnb.ProductManagement.API/Dockerfile
      args:
        BUILD_CONFIG: ${BUILD_CONFIG}
    ports:
      - "8080:8080"
    depends_on:
      - airbnb-sqlserver-db
    environment:
      - ASPNETCORE_ENVIRONMENT=${BUILD_CONFIG:-Production}
    restart: always
    networks:
      - airbnb-network

  airbnb-sqlserver-db:
    image: mcr.microsoft.com/mssql/server:latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_DATABASE: 'Airbnb'
      MSSQL_USER: 'sa'
      MSSQL_PASSWORD: 'Str0ngP@ss!'
      SA_PASSWORD: 'Str0ngP@ss!'
    ports:
      - '1433:1433'
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - airbnb-network
      
  airbnb-mongo-db:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: 'airbnb'
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'rootpassword'
    ports:
      - 27010:27017
    volumes:
      - mongodb-data:/data/db
    networks:
      - airbnb-network

  redis:
    image: redis:latest
    container_name: redis-cache
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
    restart: always
    networks:
      - airbnb-network

volumes:
  sqlserver-data:
  redis-data:
    driver: local
  mongodb-data:
  
networks:
  airbnb-network:
    driver: bridge