version: "3.8"

services:
  airbnb-api:
    build:
      context: .
      dockerfile: Airbnb.ProductManagement/Airbnb.ProductManagement.API/Dockerfile
      args:
        BUILD_CONFIG: ${BUILD_CONFIG}
    ports:
      - "8080:8080"
    depends_on:
      - airbnb-sqlserver-db
    environment:
      - ASPNETCORE_ENVIRONMENT=${BUILD_CONFIG:-Production}
    restart: always
    networks:
      - airbnb-network

  airbnb-user:
    build:
      context: .
      dockerfile: Airbnb.UserManagement/Airbnb.UserManagement.API/Dockerfile
      args:
        BUILD_CONFIGURATION: ${BUILD_CONFIG}
    ports:
      - "8081:8080"
    depends_on:
      - airbnb-sqlserver-db
    environment:
      - ASPNETCORE_ENVIRONMENT=${BUILD_CONFIG:-Production}
    restart: always
    networks:
      - airbnb-network

  airbnb-order:
    build:
      context: .
      dockerfile: Airbnb.OrderManagement/Airbnb.OrderManagement.API/Dockerfile
      args:
        BUILD_CONFIGURATION: ${BUILD_CONFIG}
    ports:
      - "8082:8080"
    depends_on:
      - airbnb-sqlserver-db
    environment:
      - ASPNETCORE_ENVIRONMENT=${BUILD_CONFIG:-Production}
    restart: always
    networks:
      - airbnb-network

  airbnb-gateway:
    build:
      context: .
      dockerfile: Airbnb.Gateway/Dockerfile
      args:
        BUILD_CONFIGURATION: ${BUILD_CONFIG}
    ports:
      - "5001:8080"
    depends_on:
      - airbnb-user
      - airbnb-order
      - airbnb-api
    environment:
      - ASPNETCORE_ENVIRONMENT=${BUILD_CONFIG:-Production}
    restart: always
    networks:
      - airbnb-network

  airbnb-sqlserver-db:
    image: mcr.microsoft.com/mssql/server:latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_DATABASE: 'Airbnb'
      MSSQL_USER: 'sa'
      MSSQL_PASSWORD: 'Str0ngP@ss!'
      SA_PASSWORD: 'Str0ngP@ss!'
    ports:
      - '1433:1433'
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - airbnb-network

volumes:
  sqlserver-data:

networks:
  airbnb-network:
    driver: bridge
