name: .NET

on:
  push:
    branches:
      - 'main'
      - 'feature/*' 
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ./Airbnb.sln

    - name: Build solution
      run: dotnet build ./Airbnb.sln --configuration Release --no-restore

    - name: Run tests
      run: dotnet test ./backend/AirbnbAPI/Airbnb.UnitTesting/Airbnb.UnitTesting.csproj --configuration Release --no-build --verbosity normal
