<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Airbnb.QueryRepository\Airbnb.MongoRepository\Airbnb.MongoRepository.csproj" />
      <ProjectReference Include="..\..\Airbnb.SharedKernel\Airbnb.Application\Airbnb.Application.csproj" />
      <ProjectReference Include="..\..\Airbnb.SharedKernel\Airbnb.Connection\Airbnb.Connection.csproj" />
      <ProjectReference Include="..\Airbnb.ProductManagement.Domain\Airbnb.ProductManagement.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="MassTransit" Version="8.4.0" />
      <PackageReference Include="MassTransit.RabbitMQ" Version="8.4.0" />
      <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="7.3.1" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="BoundedContext\ProductFacilityManagement\Projections\" />
      <Folder Include="BoundedContext\ProductFacilityManagement\Queries\" />
      <Folder Include="BoundedContext\ProductFacilityManagement\QueryObjects\" />
      <Folder Include="BoundedContext\ProductFeatureManagement\Commands\CreateFeatureCommand\" />
      <Folder Include="BoundedContext\ProductFeatureManagement\Commands\DeleteFeatureCommand\" />
      <Folder Include="BoundedContext\ProductFeatureManagement\Commands\UpdateFeatureCommand\" />
      <Folder Include="BoundedContext\ProductFeatureManagement\Projections\" />
      <Folder Include="BoundedContext\ProductFeatureManagement\Queries\" />
      <Folder Include="BoundedContext\ProductFeatureManagement\QueryObjects\" />
      <Folder Include="BoundedContext\Projections\Product\" />
    </ItemGroup>

</Project>
